# Generated by Django 6.0.2 on 2026-02-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_coachavailability_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='#2ecc71', max_length=7),
        ),
    ]
