# Generated by Django 6.0.3 on 2026-03-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0008_businesshours_facilityclosure_reservation_kind_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="court",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-date", "-start_time", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticketwallet",
            options={"ordering": ["user__username"]},
        ),
    ]
