# Generated by Django 6.0.3 on 2026-03-18 07:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0010_seed_auth_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineAccountLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_user_id", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("linked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
        migrations.DeleteModel(
            name="BusinessHours",
        ),
        migrations.DeleteModel(
            name="FacilityClosure",
        ),
        migrations.RemoveField(
            model_name="tickettransaction",
            name="reservation",
        ),
        migrations.RemoveField(
            model_name="tickettransaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ticketwallet",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="coachavailability",
            options={"ordering": ["start_at", "coach_id", "court_id"]},
        ),
        migrations.AlterModelOptions(
            name="court",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-start_at", "-id"]},
        ),
        migrations.RemoveConstraint(
            model_name="reservation",
            name="uniq_reservation_court_date_start",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="customer",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="coachavailability",
            name="date",
        ),
        migrations.RemoveField(
            model_name="coachavailability",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="coachavailability",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="coachavailability",
            name="status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="color",
        ),
        migrations.AddField(
            model_name="coachavailability",
            name="court",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_availabilities",
                to="club.court",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coachavailability",
            name="end_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 18, 7, 54, 49, 923193, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coachavailability",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="coachavailability",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 18, 7, 55, 31, 219725, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="availability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="club.coachavailability",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 18, 7, 56, 33, 970290, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 18, 7, 57, 35, 672318, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coachavailability",
            name="coach",
            field=models.ForeignKey(
                limit_choices_to={"role": "coach"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="coach",
            field=models.ForeignKey(
                default=3,
                limit_choices_to={"role": "coach"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="club.court",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("canceled", "canceled")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("member", "member"), ("coach", "coach")],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lineaccountlink",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_link",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="TicketTransaction",
        ),
        migrations.DeleteModel(
            name="TicketWallet",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="kind",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="note",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="tickets_used",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_at",
        ),
    ]
