# Generated by Django 6.0.3 on 2026-03-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0011_lineaccountlink_delete_businesshours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="is_profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
