# Generated by Django 6.0.3 on 2026-03-30 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0014_level_lesson_request_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("single", "1枚購入"),
                            ("set4", "4枚セット"),
                            ("event", "イベント用"),
                            ("admin", "管理画面調整"),
                            ("legacy", "旧データ移行"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("total_tickets", models.PositiveIntegerField(default=0)),
                ("remaining_tickets", models.PositiveIntegerField(default=0)),
                ("unit_price", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "purchased_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ticket_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["purchased_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TicketConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tickets_used", models.PositiveIntegerField(default=1)),
                ("unit_price_snapshot", models.PositiveIntegerField(default=0)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "refund_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fixed_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_consumptions",
                        to="club.fixedlesson",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_consumptions",
                        to="club.reservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_consumptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="club.ticketpurchase",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
