# Generated by Django 6.0.3 on 2026-03-31 00:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0015_ticketpurchase_ticketconsumption"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("court", "コート費用"),
                            ("ball", "ボール費用"),
                            ("equipment", "テニス用機材費用"),
                            ("server", "サーバー代金"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_coach_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-id"],
            },
        ),
    ]
