# Generated by Django 6.0.3 on 2026-04-02 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0018_add_substitute_coach_to_coachavailability"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleSurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_days", models.JSONField(blank=True, default=list)),
                (
                    "selected_weekday_time_slots",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "selected_weekend_time_slots",
                    models.JSONField(blank=True, default=list),
                ),
                ("selected_lesson_types", models.JSONField(blank=True, default=list)),
                (
                    "preferred_frequency",
                    models.CharField(
                        choices=[
                            ("weekly_1", "週1回"),
                            ("weekly_2", "週2回"),
                            ("monthly_2_3", "月2〜3回"),
                            ("irregular", "不定期"),
                        ],
                        max_length=30,
                    ),
                ),
                ("free_comment", models.TextField(blank=True, default="")),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_survey_response",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "時間帯アンケート回答",
                "verbose_name_plural": "時間帯アンケート回答",
                "ordering": ["-answered_at", "-id"],
            },
        ),
    ]
