# Generated by Django 6.0.3 on 2026-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0021_add_assigned_coach_to_stringingorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stringingorder",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "ガット張り依頼",
                "verbose_name_plural": "ガット張り依頼",
            },
        ),
        migrations.AddField(
            model_name="stringingorder",
            name="tension_lbs",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
