# Generated by Django 6.0.3 on 2026-04-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0022_alter_stringingorder_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopEstimateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("racket", "ラケット"),
                            ("string", "ガット"),
                            ("accessory", "アクセサリ"),
                        ],
                        default="racket",
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("yonex", "YONEX"),
                            ("wilson", "Wilson"),
                            ("babolat", "Babolat"),
                            ("head", "HEAD"),
                            ("prince", "Prince"),
                            ("dunlop", "DUNLOP"),
                            ("tecnifibre", "Tecnifibre"),
                            ("other", "その他"),
                        ],
                        default="yonex",
                        max_length=30,
                    ),
                ),
                (
                    "main_keyword",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "main_product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("main_official_price", models.PositiveIntegerField(default=0)),
                (
                    "string_source",
                    models.CharField(
                        choices=[
                            ("official", "ガットも購入する"),
                            ("bring_in", "ガット持ち込み"),
                            ("none", "ガット不要"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "string_keyword",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "string_product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("string_official_price", models.PositiveIntegerField(default=0)),
                ("request_stringing", models.BooleanField(default=False)),
                ("tension_lbs", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_estimate_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "物販見積もり依頼",
                "verbose_name_plural": "物販見積もり依頼",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
