# Generated by Django 6.0.3 on 2026-04-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0024_shopestimaterequest_operation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopProductMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("main", "メイン商品"), ("string", "ガット")],
                        default="main",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("racket", "ラケット"),
                            ("string", "ガット"),
                            ("accessory", "アクセサリ"),
                        ],
                        default="racket",
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("yonex", "YONEX"),
                            ("wilson", "Wilson"),
                            ("babolat", "Babolat"),
                            ("head", "HEAD"),
                            ("prince", "Prince"),
                            ("dunlop", "DUNLOP"),
                            ("tecnifibre", "Tecnifibre"),
                            ("other", "その他"),
                        ],
                        default="yonex",
                        max_length=30,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("official_price", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True, default="")),
                ("product_url", models.URLField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shop商品マスタ",
                "verbose_name_plural": "Shop商品マスタ",
                "ordering": [
                    "brand",
                    "category",
                    "product_type",
                    "sort_order",
                    "product_name",
                    "id",
                ],
            },
        ),
    ]
