# Generated by Django 6.0.4 on 2026-04-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0026_shopproductmaster_specs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedlesson",
            name="court",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_lessons",
                to="club.court",
            ),
        ),
    ]
