# Generated by Django 6.0.4 on 2026-04-09 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0027_alter_fixedlesson_court"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedlesson",
            name="coach_2",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "coach"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_lessons_as_coach_2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedlesson",
            name="coach_3",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "coach"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_lessons_as_coach_3",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
