# Generated by Django 6.0.5 on 2026-05-27 03:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0031_reservation_payment_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fixedlesson",
            options={"ordering": ["start_date", "weekday", "start_hour", "id"]},
        ),
        migrations.AlterField(
            model_name="coachavailability",
            name="coach",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coachavailability",
            name="substitute_coach",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitute_coach_availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fixedlesson",
            name="coach",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fixed_lessons_as_coach",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fixedlesson",
            name="coach_2",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_lessons_as_coach_2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fixedlesson",
            name="coach_3",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_lessons_as_coach_3",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fixedlesson",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="lessonwaitlist",
            name="coach",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_lesson_waitlists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="主担当コーチ",
            ),
        ),
        migrations.AlterField(
            model_name="lessonwaitlist",
            name="substitute_coach",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitute_lesson_waitlists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="代行コーチ",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="coach",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("ticket", "チケット"),
                    ("cash", "当日受付"),
                    ("other", "その他"),
                ],
                default="ticket",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_required", "対象外"),
                    ("unpaid", "未回収"),
                    ("paid", "回収済み"),
                    ("waived", "免除"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="substitute_coach",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitute_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stringingorder",
            name="assigned_coach",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ("coach", "contractor_coach")},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_stringing_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "会員"),
                    ("coach", "コーチ"),
                    ("contractor_coach", "業務委託コーチ"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
