# Generated by Django 6.0.5 on 2026-05-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0032_alter_fixedlesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contractor_hourly_wage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
