# Generated by Django 6.0.5 on 2026-05-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0033_user_contractor_hourly_wage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachavailability",
            name="target_level_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "指定なし"),
                    ("family", "ファミリー"),
                    ("beginner", "初級"),
                    ("beginner_plus", "初中級"),
                    ("intermediate", "中級"),
                    ("intermediate_plus", "中上級"),
                    ("advanced", "上級"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="fixedlesson",
            name="target_level_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "指定なし"),
                    ("family", "ファミリー"),
                    ("beginner", "初級"),
                    ("beginner_plus", "初中級"),
                    ("intermediate", "中級"),
                    ("intermediate_plus", "中上級"),
                    ("advanced", "上級"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="lessonwaitlist",
            name="target_level_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "指定なし"),
                    ("family", "ファミリー"),
                    ("beginner", "初級"),
                    ("beginner_plus", "初中級"),
                    ("intermediate", "中級"),
                    ("intermediate_plus", "中上級"),
                    ("advanced", "上級"),
                ],
                default="",
                max_length=30,
                verbose_name="対象レベル2",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="target_level_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "指定なし"),
                    ("family", "ファミリー"),
                    ("beginner", "初級"),
                    ("beginner_plus", "初中級"),
                    ("intermediate", "中級"),
                    ("intermediate_plus", "中上級"),
                    ("advanced", "上級"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
