# Generated by Django 6.0.5 on 2026-05-28 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0034_coachavailability_target_level_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedlesson",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role__in": ("member", "contractor_coach")},
                related_name="fixed_lessons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
