# Generated by Django 6.0.7 on 2026-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0041_settlement_model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='requested_court_type',
            field=models.CharField(choices=[('sono', '西猪名公園'), ('amagasaki', '尼崎記念公園'), ('other', 'その他')], default='sono', max_length=20),
        ),
    ]
