# Generated by Django 6.0.7 on 2026-07-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0042_alter_reservation_court_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachavailability',
            name='target_level',
            field=models.CharField(choices=[('all', '全レベル'), ('family', 'ファミリー'), ('beginner', '初級'), ('beginner_plus', '初中級'), ('intermediate', '中級'), ('intermediate_plus', '中上級'), ('advanced', '上級')], default='beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='target_level_2',
            field=models.CharField(blank=True, choices=[('', '指定なし'), ('all', '全レベル'), ('family', 'ファミリー'), ('beginner', '初級'), ('beginner_plus', '初中級'), ('intermediate', '中級'), ('intermediate_plus', '中上級'), ('advanced', '上級')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='fixedlesson',
            name='target_level',
            field=models.CharField(choices=[('all', '全レベル'), ('family', 'ファミリー'), ('beginner', '初級'), ('beginner_plus', '初中級'), ('intermediate', '中級'), ('intermediate_plus', '中上級'), ('advanced', '上級')], default='beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='fixedlesson',
            name='target_level_2',
            field=models.CharField(blank=True, choices=[('', '指定なし'), ('all', '全レベル'), ('family', 'ファミリー'), ('beginner', '初級'), ('beginner_plus', '初中級'), ('intermediate', '中級'), ('intermediate_plus', '中上級'), ('advanced', '上級')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='lessonwaitlist',
            name='target_level',
            field=models.CharField(choices=[('all', '全レベル'), ('family', 'ファミリー'), ('beginner', '初級'), ('beginner_plus', '初中級'), ('intermediate', '中級'), ('intermediate_plus', '中上級'), ('advanced', '上級')], default='beginner', max_length=30, verbose_name='対象レベル'),
        ),
        migrations.AlterField(
            model_name='lessonwaitlist',
            name='target_level_2',
            field=models.CharField(blank=True, choices=[('', '指定なし'), ('all', '全レベル'), ('family', 'ファミリー'), ('beginner', '初級'), ('beginner_plus', '初中級'), ('intermediate', '中級'), ('intermediate_plus', '中上級'), ('advanced', '上級')], default='', max_length=30, verbose_name='対象レベル2'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='target_level',
            field=models.CharField(choices=[('all', '全レベル'), ('family', 'ファミリー'), ('beginner', '初級'), ('beginner_plus', '初中級'), ('intermediate', '中級'), ('intermediate_plus', '中上級'), ('advanced', '上級')], default='beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='target_level_2',
            field=models.CharField(blank=True, choices=[('', '指定なし'), ('all', '全レベル'), ('family', 'ファミリー'), ('beginner', '初級'), ('beginner_plus', '初中級'), ('intermediate', '中級'), ('intermediate_plus', '中上級'), ('advanced', '上級')], default='', max_length=30),
        ),
    ]
