# Generated by Django 6.0.7 on 2026-07-19 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0047_alter_stringingorder_assigned_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringingorder',
            name='assigned_coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'full_name__in': ('飯塚研太朗', '清水峻平'), 'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stringing_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
