# Generated by Django 6.0.2 on 2026-08-27 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0064_court_available_court_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanted_item', models.TextField()),
                ('status', models.CharField(choices=[('inquiring', '問い合わせ中'), ('quoted', '見積済み'), ('purchase_requested', '購入希望'), ('purchased', '購入確定'), ('canceled', '取消')], default='inquiring', max_length=30)),
                ('quoted_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True, default='')),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_coach', models.ForeignKey(blank=True, limit_choices_to={'role__in': ('coach', 'contractor_coach')}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_shop_inquiries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShopQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=24, unique=True)),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('draft', '下書き'), ('sent', '見積済み'), ('purchase_requested', '購入希望'), ('purchased', '購入確定'), ('canceled', '取消')], default='sent', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shop_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_quotes', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='club.shopinquiry')),
            ],
            options={
                'ordering': ['-quote_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShopPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('confirmed', '購入確定'), ('canceled', '取消')], default='confirmed', max_length=20)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_purchases', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_shop_purchases', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='club.shopquote')),
            ],
        ),
        migrations.CreateModel(
            name='ShopQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('list_price', models.PositiveIntegerField(default=0)),
                ('sale_price', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='club.shopquote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopRevenueAllocationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_snapshot', models.JSONField(default=list)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_allocation_audits', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_audits', to='club.shoppurchase')),
            ],
        ),
        migrations.CreateModel(
            name='ShopRevenueAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role__in': ('coach', 'contractor_coach')}, on_delete=django.db.models.deletion.PROTECT, related_name='shop_revenue_allocations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shop_allocations', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='club.shoppurchase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('purchase', 'coach'), name='unique_shop_purchase_coach_allocation')],
            },
        ),
    ]
