# Generated by Django 6.0.2 on 2026-08-31 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0066_shop_cost_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedLessonCanceledOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField(verbose_name='中止日')),
                ('canceled_at', models.DateTimeField(auto_now_add=True, verbose_name='中止日時')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_fixed_lesson_occurrences', to=settings.AUTH_USER_MODEL, verbose_name='中止操作ユーザー')),
                ('fixed_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_occurrences', to='club.fixedlesson', verbose_name='固定レッスン')),
            ],
            options={
                'verbose_name': '固定レッスン中止開催回',
                'verbose_name_plural': '固定レッスン中止開催回',
                'ordering': ['occurrence_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('fixed_lesson', 'occurrence_date'), name='unique_canceled_fixed_occurrence')],
            },
        ),
    ]
