# Generated by Django 6.0.2 on 2026-09-07 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0070_shop_quote_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppurchase',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='shoppurchase',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shoppurchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('guest_name', '')), models.Q(('customer__isnull', True), models.Q(('guest_name', ''), _negated=True)), _connector='OR'), name='shop_purchase_exactly_one_buyer'),
        ),
        migrations.AddConstraint(
            model_name='shopquote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('guest_name', '')), models.Q(('customer__isnull', True), models.Q(('guest_name', ''), _negated=True)), _connector='OR'), name='shop_quote_exactly_one_buyer'),
        ),
    ]
